[project]
name = "prefect-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prefect>=3.1.13",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
